var Duma = (function() {
  var bsc = [
      "Százötvenezerbe kerül egy jobb rókabunda. Van olcsóbb is, csak az harap."
    , "A nők vigaszt nyújtanak, amire nélkülük soha nem lenne szükségünk."
    , "Optimista: Trabantos vonóhoroggal."
    , "Ne olvasd a történelmet - Csináld!"
    , "Nem hittem a kereszténységben egészen addig, míg rá nem jöttem, hogy én vagyok az Isten."
    , "Ha van valami, amit egy keselyű mindennél jobban utál, az az üvegszem."
    , "A barátnőm méretei: 1024x768x256"
    , "Meghalni nem is olyan rossz, de másnap szörnyen érzed magad."
    , "Ne okozzunk autóbalesetet az utakon - Vezessünk a járdán."
    , "Kerüld a másnaposságot - Maradj részeg!"
    , "Érdeklődés hiányában a holnap elmarad..."
    , "Egy colt mindig erősebb, mint az ászpóker."
    , "Mindent ki kell próbálni egyszer, kivéve a vérfertőzést és a népi táncot."
    , "A csapatmunka az, amikor sokan csinálják azt, amit én mondok."
    , "A házasság olyan bűn, hogy még az egyház is megtagadja a feloldozását."
    , "Program: Kijavítás céljából készült szellemi termék."
    , "Ki látott már olyan farkast, aki óvatosan üvöltözik?"
    , "Két dolog fejleszti az emberiséget: a lustaság és a rosszindulat."
    , "A halhatatlanság mulandó, de a mulandóság örök."
    , "Olyan barokkul érzem magam."
    , "Csak a hülyék agresszívek. Elhiszed, vagy kiverjem a fogaid !?!"
    , "Ó, ha Isten legalább valami konkrét jelet adna. Mondjuk egy nagy összegű betétet nyitna a nevemre egy svájci bankban..."
    , "Megtettem már a magamét a társadalomért; nem tervezem, hogy újra dolgozzam."
    , "Akik az országot vezetni tudnák, azok vagy taxisofőrök, vagy fordásznők."
    , "A Windows csak a primitíveknek és a lustáknak nyújthat élvezetet."
    , "A hegedűszó az emberiség azon kísérlete, hogy felakassza magát kötél nélkül."
    , "Az oktatás célja előidézni azt a lehető legnagyobb mértékű neurózist, amit az egyén még összeroppanás nélkül kibír."
    , "Ma kezdődik életed hátralevő része."
    , "Ha lopják az ötleteidet, akkor jó programozó vagy."
    , "Ha valami nem sikerül elsőre, nevezd el v1.0-nak!"
    , "Ha te szólsz Istenhez: imádkozol; ha Isten szól hozzád: skizofrén vagy."
    , "A zseni nem tanul, hanem tud!"
    , "Ha valaki olyan nagy, mint én, nehéz szerénynek lenni."
    , "A puszta lét nem lehet az élet célja... az túl szörnyű lenne..."
    , "Ne makacskodj! Forogj együtt a Földdel!"
    , "A hardware az, amibe bele lehet rúgni."
    , "Minden reggel megvárom amíg megjön az újság. Megnézem a halálozási rovatot, és ha nem vagyok benne, elmegyek dolgozni."
    , "Nevetés nélkül ilyen jól még nem mulattam."
    , "Tényleg csúnya lány volt. Az arca Louis Armstrong hangjára emlékeztetett."
    , "Zuhanó repülőgépen nincsenek ateisták."
    , "A memória az, amivel felejtünk."
    , "... hova tűnnek a szavak, amiket kiradírozunk?"
    , "Két dolog van a világon, amit rettenetesen utálok: az egyik a fajgyűlölet, a másik a cigányok..."
    , "Ne egyél a sárga hóból!"
    , "Némely atomerőmű körül drótháló biztosítja a sugárvédelmet."
    , "A specialista olyan ember, aki a szó szoros értelmében hülye."
    , "A tiszta stílus mögött sok a piszkozat."
    , "A nőknek biztos azért lassabb a felfogásuk, mert Windows alatt futnak."
    , "A nagyapám amúgy igen jelentéktelen ember volt. A temetésén a halottaskocsi ment leghátul."
    , "Ha valaki roppant fontosnak tartja a munkáját, az a közelgő idegösszeroppanás biztos jele."
    , "Azért iszom, hogy mások érdekesek legyenek."
    , "Csak mert paranoiás vagy, még nem biztos, hogy nem akarnak elkapni."
    , "A propaganda szerint a foghúzás ínycsiklandozó."
    , "... és a rengeteg hátránya mellett van egy csomó rossz tulajonsága is..."
    , "Nem kellene eltakarítani innen ezt az egész bagázst, és mindent előröl kezdeni valami másfajta állattal?"
    , "A mazsola egy rémült arcú szőlőszem."
    , "Lehet, hogy a mennyország jó hely, de a pokolban több az ismerős."
    , "A Microsoft végre előállította a program nélküli hibát."
    , "A valóság azoknak való, akik nem bírják a kábítószert."
    , "Ha nem lennének zsebtolvajok, úgyszólván egyáltalán nem lenne nemi életem."
    , "Mi az ördögöt kezdene magával az ember, ha valami nem állna mindig az útjába?"
    , "Hogy higgyek Istenben, amikor épp a múlt héten egy villanyírógép kocsija becsípte a nyelvemet?"
    , "Ne hidd, hogy Isten segíteni fog! Nagyon elfoglalt vagyok manapság..."
    , "Ha a kacsa nem tud úszni, nem a víz a hülye!"
    , "Láttam már ennél jobban szervezett pánikot."
    , "Honnan tudom majd, hogy elfogyott a láthatatlan tintám?"
    , "Őrült, ki lehányta láncát... (és most nem győzi törölgetni)"
    , "Egy műveletlen ember számára igen hasznos idézeteket olvasgatni..."
    , "Bundád előző tulajdonosa meghalt benne!"
    , "Előttem áll az élet - Nem látok tőle semmit."
    , "Senki sem figyel rád amíg nem hibázol."
    , "Költészetnek azt nevezzük, ami nem ér ki a lap széléig a könyvben."
    , "Agy: az a szerv, amellyel azt gondoljuk, hogy gondolkodunk."
    , "A kötelet nem lehet tolni, csak húzni."
    , "Megöl ez a tapéta - Egyikünknek menni kell!"
    , "Isten él - Csak nem akar belekeveredni a dolgokba."
    , "A vallás kísérlet arra, hogy az ember kommunikáljon az időjárással."
    , "... azt hiszem jobban vitatkoznál, ha a lábam a szádban lenne..."
    , "Istenem, adj nekem türelmet - De azonnal!"
    , "Kedves utasaink! A leszállás a pilóta betegsége miatt elmarad."
    , "A tengerek azért vannak, hogy a szárazföldek között hajózi lehessen."
    , "Az a baj a világgal, hogy a hülyék mindenben holtbiztosak, az okosok meg tele vannak kételyekkel."
    , "A jövő heti lottószámok a 6, 21, 26, 42, 66."
    , "Bízhatunk abban, hogy a politikusok intelligens, bölcs, államférfihoz méltó döntéseket hoznak - de csak akkor, ha már minden más lehetőséget kimerítettek."
    , "Találmányok nélkül az élet fakó lenne és sivár, de ez nem tűnne fel senkinek."
    , "Ha egy nő meg akar tanulni vezetni, ne állj az útjába."
    , "Úriember az, aki ígéretéhez híven megmutatja a bélyeggyűjteményét."
    , "Ha nem vagy megzavarodva, akkor félreinformáltak."
    , "A teve olyan ló, amit bizottság tervezett."
    , "Már a jövő sem a régi."
    , "Reggelizni mentem. Ha nem jövök meg 12:30-ig, akkor ebédelni is elmentem."
    , "A tánc egy vízszintes irányú vágy függőleges kifejeződése."
    , "Bármi, amiben egy csöpp élvezet is van, az vagy erkölcstelen, vagy törvénysértő, vagy hizlal."
    , "Mindig túl messzire kell mennünk ahhoz, hogy megtudjuk milyen messzire mehetünk."
    , "Gyorsan egy kalapácsot, légy van a levesemben."
    , "Annak idején az észak-amerikai indiánok nagy hibát követtek el: nem gondoskodtak bevándorlási hivatalról."
    , "Az egyetlen baj a semmittevéssel, hogy sohasem tudod, mikor végeztél."
    , "A három legjobb dolog a világon: egy sör előtte, és egy cigi utána."
    , "Soha nem voltam képes befejezni semmit, de most…"
    , "Csak egyszer vagyunk fiatalok. Utána más mentséget kell találnunk."
    , "Fénymásold le az életed - ha elveszítenéd, jó, ha van róla másolat."
    , "Az öngyilkosság egyetlen, társadalmilag elfogadott formája az, ha halálra dolgozod magad."
    , "Ha az emberi agy elég egyszerű lenne ahhoz, hogy megértsük, akkor egyszerűségünkben erre már nem lehetnénk képesek."
    , "Régebben bizonytalan voltam, de most már nem vagyok benne biztos."
    , "A felelet olyan, mint a halálraítéltek utolsó pár mondata, aki ha szépeket és hatásosakat is mond, az már lényegileg semmit sem változtat a helyzetén."
    , "Akár az 'A', akár a 'B' csoport kérdései a könnyebbek, Te mindig a másikban fogsz ülni."
    , "Amivel az órán foglalkoztok, nem érdemes megtanulni. A dolgozatban úgysem (ez) lesz benne."
    , "Amikor az utolsó dolgot is sikerülne kipuskáznod, akkor kap rajta a tanár."
    , "A tanári agy NEM emberi agy!"
    , "Ha sokat tanul az ember, előbb-utóbb elfelejti - Ha nem tanul, megkímélheti magát ettől a bosszúságtól."
    , "A fodrász csak egyféle képpen tud megnyírni: úgy, hogy másnap mindenki rajtad röhög."
    , "Az orvosi igazolás olyan, mint a pénz - Lehet valódi, és lehet hamis."
    , "A jó tanuló csak rontani tud."
    , "Minden pohár csak egyféle képpen tud felboruni. - Úgy, hogy a tartalma rád ömlik."
    , "A lakás bemutatása; egy bélyeg-, vagy lemezgyűjtemény megtekintése; meghívás egy otthoni kávé elfogyasztására; stb., mind-mind szinonim fogalmak."
    , "A békés, nyugodt, kiegyensúlyozott, harmónikus, felhőtlen, stb. kifejezéseket a családi életre csakis sci-fi írók találhatták ki."
    , "Az, hogy a vizsganapodon még nem bukott meg senki, még nem jelenti azt, hogy Téged is át fognak engedni."
    , "A legnagyobb bölcsességeket és a fatális hülyeségeket mindig csak egy hajszál választja el egymástól."
    , "Az őrült emberekből azon nyomban normálisak válnak, amint egyszer ők kerülnek többségbe."
    , "A primitív embernek felesleges megmagyarázni, hogy primitív; hisz úgysem fogja megérteni, mert primitív."
    , "Ami majdnem az, az nem az."
    , "Ebben a rohadt életben TÉNYLEG mindenkinek igaza van."
    , "Milyen aranyos a kisfia! És mondja, le szokott jönni néha a csillárról?"
    , "Többet ésszel, mint erővel! Először FORMAT C: és csak utánna fűrészelj!"
    , "Ha nem mész el mások temetésére, ők sem jönnek el a tiedre."
    , "Kérem ne dobja a csikket a piszoárba. Átázik és nagyon nehéz meggyújtani."
    , "Mindenkit érhet baleset, ha idejében ott van."
    , "A halhatatlanság a sors legszörnyűbb büntetése."
    , "... és akkor a királyfi merőlegesen fókuszálódott a királykisasszonyra..."
    , "Már látom az alagút végén a fényt - De miért dudál?"
    , "Azért, mert tavasz van, még nem kell kiabálni."
    , "Minden döntésed egy hiba."
    , "Kifordítva mindenki rózsaszínű."
    , "A világűr nincs is messze. Egyenesen felfelé másfél óra alatt odaérnénk autóval."
    , "Három kiterjedés van: az idő, a tér, és a csönd."
    , "Akik dolgoznak, lusták ahhoz, hogy gondolkodjanak."
    , "Nem számít kire szavazol, a kormányt úgyis megválasztják."
    , "Az erény önmagában hordozza büntetését. A bűn önmagában hordozza jutalmát."
    , "Idős korban gyógyteát főz az ember a babérjaiból."
    , "El sem tudok képzelni ferdébb történetet, mint hogy egy királyfi egész este egy hattyút hajkurásszon."
    , "Ha te mondod, és úgy van, akkor valószínű."
    , "Nyeregbe pattant, és elvágtatott a szélrózsa minden irányába..."
    , "Ha az életben minden fontos dolgot szemmel el lehetne intézni, akkor az utcákon csak halottak, és terhes nők lennének."
    , "Mi a csudát csinálhattunk, mielőtt felfedeztük a nosztalgiát?"
    , "Az ész bajjal jár."
    , "Ich bin Partizan..."
    , "Szerencse, hogy ilyen lassan haladok, mert lehet, hogy rossz irányba megyek."
    , "Nem iszom, mert nem szeretek - Jól érzem magam tőle."
    , "A férfi jutalma a nő. A nő jutalma a tudat, hogy ő a jutalom."
    , "Az egészség valószínűleg a halál leglassabb formája."
    , "Régebben ateista voltam, de azután megismertem Magamat."
    , "Vannak körülmények, amikor hazudni a legszentebb kötelesség!"
    , "A világegyetemben csak azért van élet, mert a szénatom bizonyos különleges tulajdonsággal rendelkezik."
    , "A veréb tud repülni, mégis mennyit ül az ágon."
    , "A legtöbb ember nem jut el a 'Miért pont Én?'-től a 'Miért ne?'-ig."
    , "Jól válaszd meg az útitársaidat; lehet, hogy meg kell enned őket!"
    , "... hogy mennyi minden van a világon, amire nekem semmi szükségem sincsen..."
    , "Nem az az élvezet, ha nincs semmi dolgunk; az az igazi, ha sok van, és mégsem csinálunk semmit!"
    , "Aki másnak vermet ás, az tud valamit!"
    , "Egy diktátor szerint egy zsákutcából is lehet sugárutat csinálni."
    , "Olyan volt vele a tánc, mintha egy zongorát tologattál volna."
    , "'Felhasználói hiba! Cserélje ki a felhasználót, majd nyomjon meg egy billenytűt!'"
    , "A csúszó-mászók sohasem botlanak meg."
    , "A legnagyobb részét annak, amit tudunk, körülbelül száz embernek köszönhetjük."
    , "Semmit sem helyettesít, kivéve talán az öngyilkosságot."
    , "Ha az iskola az életre nevel, nem félek a haláltól."
    , "Az élet kegyetlen; és ezt elviselni csak az tudja, aki kegyetlenebb nála."
    , "Azt hiszem a szex jobb, mint a logika, csak nem tudom bizonyítani."
    , "Ne szavazz! Csak bátorítod őket."
    , "Mindenki tudatlan, csak más-más témában."
    , "Nem lehet 'egy kicsit' szerelmeskedni, még kevésbé egy kicsit teherbe esni."
    , "Szavazz a liberálisokra - különben lelőjük a kutyádat."
    , "A gargalizálás kitűnő módja annak, hogy megállapítsuk, a nyakunk szivárog-e?"
    , "Föld: a Naprendszer elmegyógyintézete."
    , "Nem vagyok komplett őrült - Pár darab még hiányzik..."
    , "Jobb körökben a kaviár is része a létminimumnak!"
    , "Krisztus meghalt a bűnenkért - Hát ne okozzunk csalódást neki!"
    , "Ha a szavazástól bármi megváltozna, betiltanák."
    , "Mindenki színesbőrű, különben nem látszana!"
    , "Aki nem lop az államéból, az a családját rövidíti meg."
    , "Kocogj - és halj meg egészségesebben!"
    , "A kormány öl, butít, és nyomorba dönt!"
    , "Gazdag ember is vízzel főz - Csak ő nem üresen eszi..."
    , "Védd a fákat... - ... egyél hódot!"
    , "Az alkohol öl, butít és savakkal aldehideket képez."
    , "Nem mindenki muzsikus, aki hegedűvel mászkál. /Verdi/"
    , "Kártyáinkat a sors keveri, mi meg játszunk."
    , "Az igazi optimista nem fékez a zsákutcában."
    , "Az egyetlen dolog, ami a férfiakat egymástól megkülönbözteti, az a nyakendőjük színe."
    , "Meghalt Newton, meghalt Einstein és én is nagyon rosszul érzem magam..."
    , "Ha én lettem volna Szűz Mária, nem hagyom magam."
    , "A számítógépem megver sakkban, de kickbox-ban én vagyok a jobb!"
    , "A szó elszáll, az írás olvashatatlan."
    , "Egy hivatalos állásfoglalás szerint a nulla alig több a semminél."
    , "Román tükrök eladók: 'Ha megveszed, megnézheted magad!'"
    , "Az élet hosszú, csak nem elég széles."
    , "Kórustag voltam, amíg rá nem jöttek honnan jön a zaj."
    , "Azt hiszem átfordulok, és megnézem mi van odalent."
    , "Szeretem a munkát, lenyűgöz. Képes vagyok órákig ülni, és nézni."
    , "Ha minden ésszerű lenne a földön, akkor nem is történne semmi. /Dosztojevszkij/"
    , "Ha nem vagy képes jól csinálni, legalább próbáld meg élvezni, hogy rosszul csinálod."
    , "Egyszer kipróbáltam a telefonszexet, de a lyukak túl kicsik voltak..."
    , "A világ úgy rossz ahogy van. Minek szépítsünk a dolgon?"
    , "Alapjában véve a feleségem éretlen volt. Ülök békésen a kádban, ő meg bejön és elsűllyeszti a kishajóimat."
    , "Aki korán kel, az rosszul állította be az ébresztőóráját."
    , "Vétkezz csak! - Gyónni ráérsz később is."
    , "Ha Isten számítógépes szakembernek teremtette volna az embert, akkor 16 ujjunk lenne."
    , "Élet: Nemi úton terjedő fertőzés, amelynél a halálozási arány 100%"
    , "Ne irigyelj senkit! - Nem ismered a későbbi sorsát."
    , "Ha kíváncsi vagy rá milyen lesz a feleséged 25 év múlva, nézd meg az anyósod."
    , "Ha nem a megoldás, akkor a probléma része vagy."
    , "A televízió arra való, hogy szerepeljünk benne; nem pedig arra, hogy nézzük."
    , "Ki korán kel, az hülye - menjen el orvoshoz!"
    , "Karácsony törölve. József bevallott mindent."
    , "A költészet inkább az általánosat, a történelem az egyedi eseteket mondja el."
    , "Ritkán lövök rá valakire. Nem ok nélkül tettem."
    , "Öld meg mind! - Isten majd kiválogatja."
    , "Ha biszex vagy, kapásból megduplázódnak az esélyeid egy esti randevúra."
    , "Támogasd Tasmania újraerdősítését! - Ültess el egy makkot fejjel lefelé!"
    , "Egy nőnek jobb ha szép, mintha okos; mert egy férfinak még mindig könnyebb nézelődni, mint gondolkodni."
    , "A nagy nemzetek mindig úgy viselkednek mint a gengszterek, a kicsik meg úgy, mint az utcalányok."
    , "A gyom olyan növény, aminek a hasznosságát még nem fedezték fel."
    , "Fékezzük meg az inflációt! - Lopjunk!"
    , "A telefaxunk és a titkárnőjük közül a fax volt inteligensebb."
    , "Csak a középszerűek vannak mindig elemükben."
    , "Gondosan moss kezet, ki tudja hol volt előtte a szappan!"
    , "Mi a különbség egy kacsa között?"
    , "Ha éhes vagy, nyalj sót - akkor majd szomjas leszel."
    , "Az opera az, amikor egy pasast hátba szúrnak, és az nem vérzik, hanem énekel."
    , "A sánta ember is lehet földönfutó."
    , "Megtisztel az irigységed, de nem tudom viszonozni."
    , "Ha szép a varrás a hason, még nem biztos, hogy a műtét sikeres volt."
    , "Az ÉLET nagyon drága, de az árban benne van évente egy Nap körüli utazás."
    , "A teológián és a szexen kívül nincs is igazán miről beszélgetni."
    , "Diplomata az, aki úgy küld el a fenébe, hogy szinte várod, hogy indulhass!"
    , "A pornó az elmélet, a nemi erőszak a gyakorlat."
    , "Ha nem tehetjük, amit akarunk; akkor azt kell akarnunk, amit tehetünk."
    , "Nem lehetsz részeg, ha kapaszkodás nélkül tudsz a padlón feküdni."
    , "Kérjük ne lője le a zongoristát. Minden tőle telhetőt megtesz."
    , "Mutass nekem egy embert, aki mindkét lábával a földön áll. Fogadjunk, hogy nem tudja felvenni a nadrágját."
    , "A negyedik Martini után a férjem egy gusztustalan állattá válik. Az ötödik után elájulok."
    , "Két rossz közül mindig azt választom, amit még nem próbáltam."
    , "Hamletet már vagy 5000 színész eljátszotta. - Nem csoda, hogy megőrült."
    , "Ha háromnál többször rázod, az már maszturbáció."
    , "Senki sem magányos miközben spagettit eszik."
    , "Jézus él. - Ez akkor azt jelenti, hogy nem lesz húsvéti szünetünk?"
    , "Le az inflációval! Együk meg a gazdagokat!"
    , "Mit vágsz olyan képet, mint egy megcímzetlen boríték?!?"
    , "Le az előítéletekkel! Mindenkit egyformán utálok."
    , "Az ittas repülés következménye. /egy szétkenődött szúnyog mellett a falon/"
    , "Elvtársak..."
    , "A fekete lyukak úgy keletkeztek, hogy Isten nullával osztott."
    , "Ha egy több nyelven, folyékonyan beszélő ember az egyik nyelven nyelvtanilag teljesen hibásan, pocsék kiejtéssel beszél, akkor az illetőnek az az anyanyelve!"
    , "A középút mindig széles, de van rajta halálkanyar."
    , "A költő attól bátor, hogy nyitva tartja az őrület felé vezető ajtót."
    , "Lépj be a hadseregbe, utazd be a világot, találkozz érdekes emberekkel - és öld meg őket!"
    , "A következő jelmezbálban láthatatlan leszek."
    , "A dicsfény kihuny, az ujjlenyomat marad."
    , "Mi vagyunk azok, akiktől óvtak a szüleid."
    , "Az idő nekünk dolgozott, de ma már munkanélküli."
    , "Ki mondja, hogy üldözési mániám van? És miért érdekli őket?"
    , "A helyzet reménytelen, de nem súlyos."
    , "Ne vigyél kísértésbe, oda találok magamtól is!"
    , "Befejezni egy könyvet annyi, mint kivinni egy gyereket az udvarra, és lelőni."
    , "Én nagyon szeretem a disznókat, mégsem esik nehezemre, hogy megegyem őket."
    , "Ha a cápa a tenyeredből eszik akkor a lábadból is fog."
    , "Miért konvergens a mozgólépcső? Mert monoton és korlátos."
    , "A sün makacs madár, mert csak akkor hajlandó repülni, ha belerúgok."
    , "Az emberiséget ősidők óta két dolog foglalkoztatja: 1. Ki találta fel a munkát? 2. A többiek miért nem verték agyon?"
    , "A nő olyan, mint a shareware program. Vagy a legjobb funkciói vannak letiltva, vagy korlátozott a használati ideje, vagy állandóan cseszeget, hogy regisztráltasd."
    , "A gyermek lényege: nagy hangzavar, rajta némi kosszal."
    , "Kezdetben vala a semmi. Majd az Úr mondá: 'Legyen világosság!' - s továbbra is vala a semmi, de már látni is lehetett azt."
    , "A szamárfül az origami legegyszerűbb formája."
    , "Ha az összes férfi ugyan olyan, akkor a nők miért válogatnak annyit?"
    , "Sose felejtsd el, hogy a legklasszabb csaj is össze tudja hányni az ágyad."
    , "Az ember időnként belebotlik az igazságba, de legtöbbször feltápászkodik és továbbmegy."
    , "Nem azért küzdöttem fel magam a tápláléklánc csúcsára, hogy vegetariánus legyek."
    , "Kérem, ne etessék az állatokat. Nem élnek."
    , "Zenéről írni olyan, mint táncolni az építészetről."
    , "Az alvástól megéhezem. Az evéstől elálmosodom. Az élet szép. - Garfield"
    , "Légy kedves gyermekeiddel, hiszen ők választják ki neked a szociális otthont!"
    , "Még nem számoltam össze, de azt hiszem ezermester vagyok."
    , "Műtő! A konyha üzeni, hogy siessetek a négyes beteggel!..."
    , "Az okos enged, aztán ott áll üres kézzel, és gondolkozik, hol cseszhette el."
    , "Nem tudom, mi a bajod, de fogadok, nehéz lebetűzni."
    , "Ha azért vagyunk, hogy segítsünk másokon, akkor miért vannak mások?"
    , "A szenilitásban az a legjobb, hogy saját magad elől dughatod el a karácsonyi ajándékokat."
    , "Szeretek tarotkártyákkal pókerezni... ...összeszedek egy fullt, és voilá, meghalt négy ember."
    , "A borosta nem szúr. Csak tudni kell a megfelelő oldalára születni."
    , "Megérkeztek az orvosi vizsgálat eredményei. Maga alacsony, kövér, és kopasz."
    , "Mindjárt olyat teszek ezzel az uborkával, hogy már a mondat felénél megbánom!"
    , "Ha lelövünk valakit, azzal bizonyos mértékig tisztáztuk a róla alkotott véleményünket."
    , "A Biblia arra tanít, hogy szeresd felebarátodat. A Káma Szutra pedig megmagyarázza, hogyan."
    , "A nők két nagy problémával küzdenek: nincs mit felvenniük, és nincs elegendő helyük, ahol ezt a semmit tárolhatják."
    , "Ha az összes többi bolygó holdjának van neve, a mi holdunknak miért nincs?"
    , "Nagy nap volt 2004. május 1. Magyarország számára, mert történelme során még sohasem csatoltak hozzá ekkora területet."
    , "Hogy lehet tovább gyorsítani a Windowst? Erősebben dobod, vagy magasabbról ejted."
    , "Az élet egy siralomvölgy. De vannak, akik csak a hegytetőn kaptak helyet."
    , "Lelkesedés az, amikor a nászéjszakán a vőlegény lekapcsolja a villanyt, és már az ágyban van, mire sötét lesz."
    , "Az ideális szerető reggel hétkor pizzává változik."
    , "Az ideális nő olyan mint a hold. Este jön, reggel megy."
    , "Nem is vagyok büdös. Csak életszagú."
    , "Kicsi a bors, főleg az őrölt."
    , "Ha úgy érzed, hogy ura vagy a helyzetnek, akkor ez csak azt jelenti, hogy nem vagy elég gyors."
    , "Kicsi a bors, de vannak barátai..."
    , "Ritkán látlak mint Baumgartner a kockás zászlót!"
    , "Miért hívják turistaszezonnak, ha egyet sem szabad lelőni?"
    , "A chiliszósz nem más, mint határozott fellépésű ketchup."
    , "A törökök tudják, hogy a fáknak melyik oldala Mohács."
    , "Megtorpant, mint harkály az erdőszélen."
    , "Azt nevezzük pajtásnak, akinek van pajtája."
    , "Lehet, hogy még nem is volt készen?... - csak Isten megutálta, és abbahagyta a hetedik napon."
    , "A hadseregben a kerek dolgokat viszik, a szögleteseket gurítják. De csak azért, hogy lekopjanak az éleik, kerekek legyenek, és lehessen vinni őket."
    , "A demokrácia azt jelenti, hogy mindenkinek lehetősége van a híd alatt aludni."
    , "Nem mind arany, ami hörcsög!"
    , "A cukor egy fehér anyag, ami a kávénak rossz ízt ad, ha elfelejtik beletenni."
    , "Az ember társas állat. S többnyire minél nagyobb a társaság, annál nagyobb állat."
    , "Egy embertől lopni: plágium. Sok embertől lopni: kutatás."
    , "Vegetáriánus: régi indián szó. Jelentése: 'béna vadász'."
    , "Ha egy hupikék törpikét fojtogatok, milyen szine lesz?"
    , "Amit ma megtehetsz, halaszd holnaputánra! És lesz két szabadnapod..."
    , "Egy férfi nő nélkül olyan, mint egy hát púp nélkül."
    , "A káros szenvedélyekben óriási lehetőség van: le lehet szokni róluk."
    , "Automata esernyő? Az semmi, nekem dobtáras van."
    , "Az emberek ritkán ismerik fel a kedvező alkalmat, mert általában kemény munka formájában teszi tiszteletét."
    , "Nem örülök, hogy sikerült a kezelésem. Tavaly még én voltam Napóleon, most meg csak Kovács Attila."
    , "Ha az ember bőrét egy centis csíkokra vágnák, és az egyenlítő mellett kiterítenék, nagyon hülyén nézne ki..."
    , "Néha rámtörnek az anyai ösztönök, például amikor fekszem a kanapén és nem érem el a tévé távirányítóját, arra gondolok: 'Ember, de jó lenne most egy gyerek.' -Kathleen Madigan"
    , "Az állatvédők azért vannak a szőrmebundák és nem a bőrkabátok ellen, mert könnyebb idős hölgyeket molesztálni, mint a Pokol Angyalait."
    , "Rögtön maga jön, csak elvitték élezni a bárdot..."
    , "Mindig a hülye ötletek valósulnak meg a leggyorsabban."
    , "Arra, hogy 'Jó reggelt!' nem a 'Bizonyítsd be!' a helyes válasz."
    , "Ha felveszem a fejhallgatót, miért nem a fejemet hallom?"
    , "Akar igen/nem promptot? (i/n)"
    , "Írtam egy emailt a babbage.museum.london.uk szerverről, és most ROHADTUL FÁJNAK AZ UJJAIM!"
    , "A kör az ugyanahhoz a ponthoz vezető leghosszabb út."
    , "Az engedély nélküli bevándorlók mindig is gondot okoztak Amerikában. Kérdezzék csak meg az indiánokat."
    , "Ha bal lábbal keltél, legalább annak örülj, hogy van bal lábad!"
    , "Szép és fiatal nőt kell elvenni, mert az legalább hamar otthagy."
    , "A pulóver az a ruhadarab, amelyet a gyereknek haladéktalanul fel kell venni, ha fázik a mama."
    , "Nincs is garvitáció, a Föld csak szivat minket!"
    , "Napról napra az újdonság varázsával ajándékoz meg az amnézia."
    , "Kapnak a súlyos égési sérülésben elhunytak kedvezményt a hamvasztásnál?"
    , "Nyelvészek és szexológusok észrevételezték, hogy nincs egy normális szavunk a női nemiszervre. Amit használunk, az vagy obszcén, vagy orvosi műszó. Én találtam egyet: élménycentrum."
    , "A kutyán kívül a könyv az ember legjobb barátja. A kutyán belül olyan sötét van, hogy nem lehet olvasni."
    , "Száztíz éves koromban akarok meghalni, egy féltékeny férj golyója által."
    , "Egy kutya olcsóbb, mint egy feleség. Kevesebbet eszik és már bundája is van."
    , "Szörnyen nézel ki! Ez most a divat?"
    , "Engem nem lehet elképzelni, engem ki kell próbálni!"
    , "Milyen jó, hogy pufferelve vagyunk. Különben egész nap a WC-n ennénk."
    , "Ha megígérem, hogy hiányozni fogsz, elmész?"
    , "Aki utoljára nevet, annak 56k-s modeme van."
    , "Ha elsőre nem sikerül, nézz utána, hátha a vesztesnek is jár valami."
    , "Miért kell leszögezni a koporsókat?"
    , "A vita nemesít... Végső esetben pedig ott a láncfűrész..."
    , "Könnyű a bolhából elefántot csinálni. Etetni viszont már nehezebb."
    , "Létezik még vasutas humor. Persze most nem arra gondolok, amikor a kalauz az utolsó kocsiból integet a lemaradottaknak... /Rejtő/"
    , "Tegnap abbahagytam a piálást, a dohányzást és a szexet. Az volt életem legrosszabb húsz perce."
    , "Némelyek sokkal későbbi leszármazottai a csimpánznak mint mások."
    , "Modern irodalmat olvasni olyan, mintha az ember megpróbálná követni a cselekményt a betűlevesben."
    , "A férfiak azért alszanak el gyorsan szex után, mert előtte fél éjszakát könyörögnek érte."
    , "Elfelejtettem a telefonszámom, megmondanád a tied?"
    , "A mártíromság az egyetlen út, hogy tehetség nélkül híres legyél."
    , "Az egyetemen én vagyok az Isten. Mindenki tudja, hogy létezem, de még senki sem látott."
    , "Ne ébressz fel, épp rólad álmodom."
    , "Mi annyira elmaradottak vagyunk, hogy nálunk a szivárvány is fekete-fehér."
    , "A skótduda a zaj és a zene közti hiányzó láncszem."
    , "Az iskolában akkor kaptam volna legkönnyebben ötöst, ha megmérik a véralkohol szintemet."
    , "Nem iszom, nem dohányzom, nem nőzöm, minden nap hatkor kelek. De mindez majd meg fog változni, amint kikerülök a börtönből."
    , "Olyan kétségbeesetten fuldokolt, hogy végül a kötél másik végét is odadobtam neki."
    , "A lottó nem más, mint a matekból gyenge emberekre kirótt adó."
    , "Ha azt gondolod, hogy Oidipusznak problémái voltak, úgy emlékezz arra, hogy Ádám volt Éva anyja!"
    , "Honnan ez a mérhetetlen bizalmatlanság benned? Lehet, hogy ez a szúnyog éppen vért akar adni neked."
    , "Örvendezzünk, és legyünk hálásak, amiért Isten nem adja meg nekünk mindazt, amit kérünk..."
    , "Azért jó a mazohistának, mert ha rossz, akkor jó. Ha meg jó, akkor rossz, de az jó."
    , "Hogy mit csinálna ma Elvis, ha élne? Kaparná a koporsót!"
    , "A kisbaba olyan mint a Nescafe. Könnyű megcsinálni és egész éjjel ébren tart."
    , "Ha hülyeség, de működik... lehet, hogy annyira mégsem hülyeség."
    , "Ki korán kel egész nap álmos."
    , "Mit csinált az ember épp akkor, mikor felfedezte, hogy a tehenek tejet adnak?"
    , "A limonádé egy értelmetlen ital: először citromozzuk, hogy savanyú legyen aztán cukrozzuk, hogy édes."
    , "Mindenki jó valamire. Ha másra nem, hát elrettentő példának."
    , "Annyira tettrekész vagyok, hogy a nevem valójában ige kellene, hogy legyen."
    , "Az igazi punkok átsegítik az idős hölgyet a zebrán, mert azon több ember döbben meg, mintha a járdára hányáson."
    , "Agyon lehet ütni az anyóst törölközővel? Igen, csak jól bele kell csavarni a vasalót."
    , "A házasság jelmondata: Szeretkezz és Háborúzz!"
    , "Míért nem ütötte agyon Noé a két szúnyogot?"
    , "Egy csomó olyan segédeszköz létezik, amivel a nők szexuális kedve növelhető. Itt van például a Mercedes-Benz 380SL."
    , "Ha nem találod a tűt, gyújtsd fel a szénakazlat."
    , "A legsötétebb óra is csak 60 percből áll."
    , "A neten szörfözés kezdőknek való. Én cirkálok."
    , "Neked is **** a pin kódod?"
    , "Egy jó nőt meghódítani és nem elmesélni olyan, mint titokban átúszni a Csendes-óceánt."
    , "Mi nem haldoklunk. Mi így élünk."
    , "Az idegbaj öröklődő betegség. Én is a gyerekeimtől kaptam."
    , "Sose vegyél semmit aminek nyele van. Azzal dolgozni kell."
    , "Kérem nyomja meg a CTRL-SHIFT-ALT-DEL-PGUP-ESC-F11-et hogy..."
    , "Backup not found! (A)bort, (R)etry, (P)anic?"
    , "Fatal System Error: Press F13 to continue..."
    , "Az alkoholizmus nem más, mint örökös harc a másnaposság ellen."
    , "Golyó általi halálnak nevezzük, amikor belepusztulsz a tökönrúgásba."
    , "Hányatott gyermekkorom volt. Valószínüleg a répafőzeléktől."
    , "Egy tökéletes férfi hajlandó órákon át várni, míg a barátnője két perc alatt elkészül."
    , "A munkanélküliség az a tevékenység, amit ha reggel felébredsz, azonnal csinálnod kell."
    , "Fölösleges, mint szőke nőnek gondolkodási időt adni."
    , "Ha beleteszed a kezed egy pohár kénsavba, észlelni fogod, hogy a pohárnak nincs alja."
    , "Megszabadultam a gyerektől, a macskám ugyanis allergiás volt rá."
    , "Muszáj mindig megoldást találni? Nem élvezhetnénk egy kicsit a problémát?"
    , "Gondolkodom, tehát nőtlen vagyok."
    , "Egy kutya olcsóbb, mint egy feleség. Kevesebbet eszik és már bundája is van."
    , "Isten csak azért nem bocsát ránk megint özönvizet, mert látja, hogy az elsővel sem ért semmit."
    , "Olyan jó vagyok az ágyban, hogy néha már a saját nevem sikongatom."
    , "Megérkeztek az orvosi vizsgálat eredményei. Maga alacsony, kövér, és kopasz."
    , "Haverok, Buli, Kannásbor..."
    , "A férfiak nélkül a világ teli lenne boldog, kövér nőkkel."
    , "Egy macskát mindenre megtaníthatsz, amit ő szeretne csinálni."
    , "Az élet egy olyan színdarab, amit Isten írt és Murphy rendezett."
    , "Klasszikus - olyan könyv, amit az emberek dicsérnek, de nem olvasnak."
    , "Imádom nézni a játszótéren szertelenül ugrándozó gyermekeket. Nem tudhatják, hogy vaktölténnyel lövöldözök rájuk."
    , "Azt az embert nevezzük lépcsőház-típusnak, aki sötét és korlátolt..."
    , "Aki másnak vermet ás, hamar elfárad..."
    , "A Bíborszívet azért kapod, mert elég okos voltál tervet kovácsolni, elég hülye voltál kipróbálni, és elég szerencsés voltál ahhoz, hogy túléld."
    , "Kicsi a bors, de hol a fenében van?"
    , "A férjem és én vallási okok miatt váltunk el: azt hitte, ő az Isten..."
    , "Sikerbiztos módszer elefántszobor elkészítéséhez: szerezzünk egy hatalmas tömb márványt és faragjunk le róla mindent, ami nem hasonlít az elefántra."
    , "A holland nyelv onnan származik mikor egy részeg angol németül akart beszélni."
    , "Én olyan optimista vagyok, hogy elindulnék egy csónakkal Moby Dick után, és még tartármártást is vinnék magammal. /Zig Ziglar/"
    , "A tudás bűn, de én ártatlan vagyok..."
    , "Ha a templom Isten háza, akkor miért van rajta villámhárító?"
    , "Kíváncsiak lennénk az Ön, mint kívülálló véleményére az intelligenciáról!"
    , "Kínos pillanat az, amikor az ember kiköp a csukott autóablakon..."
    , "Nem tudtam, hogy lehetetlen, ezért megcsináltam."
    , "Ha meg tudod magyarázni, miért szeretsz egy nőt, nem is szereted igazán."
    , "Mi a fenét csinált Isten a teremtés előtt?"
    , "A víz 0°-on nagyon hideg."
    , "Ha a jövő tudná, mi vár rá, soha nem jönne el."
    , "Mindenhol jó, de legolcsóbb otthon."
    , "Ha azt mondom, hogy 'mi', biztos úr, azalatt magamat, a négy ifjú hölgyet és természetesen a kecskét is értem."
    , "A Föld 98%-a megtelt. Kérem törölje, akit csak tud."
    , "Szégyen a futás, és fárasztó."
    , "A részegség az, amikor három ember beül egy szobába, megisznak egy-egy üveg Whiskyt, az egyikük kimegy, a másik kettő pedig megpróbálja kitalálni, hogy melyikük ment ki."
    , "Az élettel az a probléma, hogy mikorra nyitott könyvként tudnál a nőkben olvasni, lejár a könyvtár tagságid."
    , "Mi annyira elmaradottak vagyunk, hogy nálunk a szivárvány is fekete-fehér."
    , "Éjjel azt álmodtam, hogy megettem öt kiló vattacukrot, aztán amikor felkeltem, nem volt meg a párnám."
    , "Hogy lehet felizgatni egy öregasszonyt? El kell venni a nyugdíját!"
    , "Egy nap 24 óra, egy ládában 24 sör van. Ez nem lehet véletlen..."
    , "Ne igyál, amikor vezetsz! Még nekimész valaminek és kilöttyen a pia."
    , "Jobban szeretlek, mint a majonézt."
    , "A Vodafone-nak, olyan szar a Westel-je..."
    , "Én nem lehetek pesszimista... nekem az úgy se menne..."
    , "Lehet, hogy a sas magasan szárnyal, de a vakondot sose darálja be gázturbina..."
    , "Nem kérek villanyírógépet, nem nyírok villát."
    , "Meg van zavarodva mint Ádám anyák napján."
    , "A lift életpályája az utolsó felvonásban teljesedik ki."
    , "Ön dönt, iszik vagy vezet! De egyszerre a hármat ne csinálja!"
    , "Ha az építőipar úgy építene, ahogy a programozók készítik programjaikat, az első jöttment harkály lerombolhatná az egész emberi civilizációt."
    , "A romantikusok légvárat építenek, a depressziósak beköltöznek, a pszichológusok beszedik a lakbért, a pszichopaták meg betörik az ablakot."
    , "A nők sosem vadásznak a férfiakra. Viszont az egérfogó sem vadászik az egerekre, mégis ugyanaz az eredmény."
    , "Végy egy nőt... öntsd le babaolajjal..."
    , "A nő kedvenc pozíciója: igazgató."
    , "Ki a kicsit nem becsüli - lopjon nagyobbat!"
    , "Isten megteremtett engem, mert van szépérzéke és megteremtett téged, mert van humorérzéke is!"
    , "Magyarországon azért ilyen lassú a vasúti közlekedés, mert meg kell őriznünk a nagy ország látszatát!"
    , "Igenis vannak érzéseim. Most is érzem, hogy éhes vagyok."
    , "Mindegy, hogy Suzuki-t vagy Ferrari-t kapsz karácsonyra mindegyik a te autód lesz."
    , "Reggel nem tudott enni, mert olyan szerelmes volt, délben nem tudott enni, mert olyan szerelmes volt, este nem tudott aludni, mert olyan éhes volt."
    , "Sötét vagy, mint a vakond belső zsebe."
    , "Amikor először belenéztem egy szótárba, azt hittem, hogy ez egy vers, ami mindenről szól."
    , "Ahányszor a homokozóban játszottam, a macska mindig megpróbált betemetni."
    , "Szeretem az életet. Legalább van mit csinálni."
    , "Szeresd az ellenséged - bele fog dilizni."
    , "OK, megjöttem. És most halljam a másik két kívánságod."
    , "Ha fürdés után tiszták vagyunk, miért kell kimosni a törülközőt?"
    , "A Bibliában hat figyelmeztetés vonatkozik a homoszexuálisokra, és háromszázhatvankettő a heteroszexuálisokra. Ez nem azt jelenti hogy Isten nem szereti a heteroszexuálisokat. Csak azt, hogy nekik több irányításra van szükségük."
    , "Az izé mintájára micsinált bigyó."
    , "A villa egy olyan eszköz, amelyet főképp arra használunk, hogy halott állatokat tegyünk vele a szánkba."
    , "Ez az elv olyan tökéletesen általános, hogy nem is lehetséges speciális alkalmazása."
    , "A sör női hormonokat tartalmaz: 10-15 üveg után a férfiember már nem tud logikusan gondolkodni, és autót vezetni."
    , "A Biblia mindig is a legnagyobb bestseller volt. Képzeljük csak el, mi lenne, ha rányomnák az elejére a 'Javított kiadás' feliratot..."
    , "A legügyesebb állat az ürge, hiszen búzával teli pofazacskóval is képes repülni, miközben egy sast egyensúlyoz a hátán."
    , "A Balatonban mindenhol leér a lábam! Legfeljebb a fejem nem lóg ki..."
    , "A kompatibilitást, mint üveggolyót megkapod, csak hunyd le kis szemed..."
    , "A/4-es papírlapomat hasonló kategóriájú Audi-ra cserélném."
    , "10 fajta ember van. Aki tud számolni bináris számrendszerben, és aki nem."
    , "Otthon ezt ne próbáljátok ki. Menjetek át inkább a szomszédhoz."
    , "A lucfenyő magyarul karácsonyfa."
    , "A macskafürdetés: harcművészet."
    , "Egy költő így mondta: 'fát csak Isten teremthet.' Talán azért, mert nagyon nehéz kitalálni, hogyan tegyük rá a kérgét."
    , "Aki holnapra behoz 10 működő vulkánt, kap egy ötöst!"
    , "Az infúzió a leghosszabb evőeszköz."
    , "A bánatomat italba akartam folytani, de tud úszni az a bestia."
    , "Mióta feltalálták a tükröt nem kell másokon röhögnöd."
    , "Én nem szeretem az uborkát, és nagyon örülök, hogy nem szeretem, mert ha szeretném, akkor megenném, pedig nagyon utálom."
    , "Ha Isten nem pusztítja el a Hollywood Boulevard-ot, Szodomáért és Gomorráért tartozik egy bocsánatkéréssel."
    , "Még nincs teljesen kész, de már majdnem elkezdtük..."
    , "Meg ne buktassátok a kormányt, amig haza nem jöttünk. /egy nyaraló/"
    , "Csapatban dolgozni fontos. Legalább van kire lőnünk."
    , "A nők olyanok, mint a pizza. A húsos jobb, mint a gombás."
    , "Ha jelen lehettem volna a teremtésnél, adhattam volna néhány hasznos tanácsot."
    , "O.K., megjöttem. És most halljam a másik két kívánságod."
    , "A bunkóságnak is van határa, csak mi nem ismerjük!"
    , "A róka és a holló meséje arról szól, hogy a húsevő róka és a rovarevő holló veszekednek egy tejterméken, amit mind a ketten utálnak."
    , "Óvszerautomatán: Apu szerint mind rossz..."
    , "És Jézus szóla hozzájuk: 'Mondjátok, ki vagyok én?' És ők felelék: 'Te vagy létünk alapjának eszkatológiai manifesztációja, a kerigma, amiben interperszonális kapcsolataink legvégső értelme tárul fel előttünk.' És Jézus szóla: 'He???'"
    , "A katolikus vallás sajátossága, hogy az emberek vasárnaponként meggyónják azokat a bűnöket, amelyeket a következő héten újra és újra elkövetnek."
    , "Aki tud és tudja, hogy tud, az veszélyes, attól óvakodjatok! Aki nem tud és tudja, hogy nem tud, az okos azt tanítsátok! Aki tud és nem tudja, hogy tud, az bölcs, attól tanuljatok! Aki nem tud és nem tudja, hogy nem tud, az hülye, azt hagyjátok!"
    , "Gentleman az, aki megtanult tangóharmonikázni, de nem teszi."
    , "A pofon egy elhadart simogatás."
    , "Ami nincs odaszegezve az az enyém. Amit fel tudok feszíteni, az nincs odaszegezve..."
    , "Rossz az embernek egyedül. Nincs aki untassa."
    , "A bárpultos tulajdonképpen orvos, csak korlátozott gyógyszerarzenállal."
    , "A limonádé mesterséges aromákat tartalmaz, ellenben a bútorápoló szerek valódi citromot."
    , "Floppyról bootolt (azelőtt: bal lábbal kelt fel)."
    , "A konzervatívok nem engedik megváltoztatni azt, amiért a liberálisokként egy generációval ezelőtt küzdöttek."
    , "Vállalj gyereket! 5 évig tart, míg megtanítod rendesen járni és beszélni; aztán még 15 évig, míg végre befogja a száját és leteszi a seggét."
    , "A kutya a hűség jelképe mégis pórázon tartjuk."
    , "A szőke nők nem hülyébbek a többinél, csak alacsonyabb az IQ-juk."
    , "Ha sárga és villog, az japán turista..."
    , "Soha sehol nem szeretné annyira az ember, ha az életnek volna egy 'gyors előre' gombja, mint egy katolikus esküvőn."
    , "Az unalmas játék is használható valamire. Lehet vele unatkozni!"
    , "A rasszizmus mindenütt jelen van... A zongora fekete billentyűi rövidebbek!"
    , "Könnyedség, erő, szellem. Ez vagyok én! /droID:242/"
    , "Nagyon kellemetlen dolog egyszerre kifogyni a sebességből, a magasságból, és az ötletekből."
    , "A papoknak vajon miért kötelező fél évente gyónni?"
    , "Akiből embert faragnak, az szétforgácsolódik."
    , "Az állatok milyen furcsák. A kutya felnéz rád. A macska lenéz rád. Csak a disznó szemében vagy egyenrangú."
    , "Olyan nincs, hogy valami nem sörnyitó!"
    , "Házasság? Nem szaporodom fogságban!"
    , "A természetesen matreializálódott periférikus komlexum a pszeudoindividualisztikus egocentrumban hivatott kiváltani a 'de jó baszni' érzést."
    , "Élni annyi, mint röhögni az életen és belehalni a röhögésbe!"
    , "Nem jön semmi, csak egy tehén... Az is IFA-n."
    , "A stressz az, amikor üvöltve ébredsz fel, aztán rájössz, hogy nem is aludtál."
    , "Hogy mit csináljunk? - kérdezte az ókori kínai faltervező mérnök."
    , "A vakok nem tudják lenézni az embert."
    , "A barátaim mindent megdugtak, ami mozgott, de én nem tartottam fontosnak, hogy ilyen korlátokat állítsak magamnak."
    , "A pénz az ördög találmánya, de ha sok van belőle, az maga a mennyország."
    , "Aki egyszer van a tévében, az maximum TV szerelő... De a ki már kétszer, az kérem szépen SZTÁR!"
    , "Én ilyennek születtem. Mi a te mentséged?"
    , "Ahányszor a homokozóban játszottam, a macska mindig megpróbált betemetni."
    , "A kínai nép egy nagy család, ahol mindenki hasonlít mindenkire."
    , "Az alkohol elterelte a gondolataimat... Nem, inkább kiirtotta őket..."
    , "Akármilyen rossz is a kölyök, adókedvezménynek megteszi."
    , "A tiszta lelkiismeret általában a rossz emlékezet jele."
    , "Kétféle ember létezik: az egyik mindig megmondja, amit gondol. A másiknak vannak barátai."
    , "Mondtam a fogorvosnak, hogy sárgák a fogaim. Azt tanácsolta, viseljek barna nyakkendőt."
    , "Még nem vagyok 30, csak 24 plusz áfa."
    , "Jöttem, láttam és most nem győzök bocsánatot kérni."
    , "Ismertem egy olyan ronda pasit, hogy amikor e-mailben elküldte a fényképét, felismerte az antivírus..."
    , "Jöttek a törökök. Annyian voltak, mint az oroszok."
    , "Nem minden az, aminek látszik. Noé bárkáját amatőrök építették. A Titanicot profik."
    , "Csak tudnám, mit szerettek a nők a férfiakban, mielőtt feltalálták a pénzt."
    , "Azt az embert nevezzük lépcsőház-típusnak, aki sötét és korlátolt..."
    , "Nincs semmi élvezet abban, ha olyan embert akasztunk fel, akinek nincs ellene kifogása."
    , "Autószerelő: Nem tudtam megcsinálni a féket, így hangosabbra állítottam a dudát!"
    , "Ha a gyengébbik nemnél be akarsz vágódni, mondd nekik, hogy impotens vagy. Alig várják, hogy megcáfolhassák. /Cary Grant/"
    , "A pénz az ördög találmánya, de ha sok van belőle, az maga a mennyország."
    , "Mi a fenét csinált Isten a teremtés előtt?"
    , "Rend csak ott van, ahol az emberek lusták valamit megkeresni."
    , "Valahányszor randevúzom egy férfival, mindig arra gondolok, hogy valóban azt akarom, hogy ezzel a férfival töltsék a gyerekeim a hétvégéket?"
    , "A páciens visszautasította a boncolást..."
    , "A nejem olyan kövér, hogy az állatkertben az elefántok perecet dobáltak neki."
    , "Öngyilkosságot akar elkövetni? Mi segíthetünk! (egy városi busz oldalán)"
    , "A legcsodálatosabb festmény is csak fél kiló festék szétkenve."
    , "Néhány hiba akkora poén, hogy kár lenne csak egyszer elkövetni őket."
    , "Az ember beágyaz, elmosogat, aztán fél év múlva kezdheti elölről az egészet."
    , "Akkora paraszt vagy, hogy érted amit a Győzike mond!"
    , "A szülők azért találták fel a szexet, mert az az undok kölök nem adta oda a játékát."
    , "Inkább csináld holnap. Ma már eleget hibáztál!"
    , "Nem szabad azt mondani, hogy cigány. Van rá egy új szakkifejezés: familiárisan hiperpigmentált."
    , "A nőknek is van joguk programozni, vegyünk nekik mosógépet!"
    , "Sosem gondoltam volna, hogy a bank egy vidám munkahely. Először csak kedvesen mosolyogtak, aztán mikor meghallották mennyi hitelt szeretnék felvenni, kitört a röhögés."
    , "Amíg a körömlakk meg nem szárad, a nő gyakorlatilag védtelen."
    , "Tesco: Tudományosan Elcseszett Selejt Cuccok Osztogatása"
    , "Ne igyál és vezess, hanem drogozz és repülj!"
    , "Én már a következő rendszert is utálom."
    , "Csak tudnám, miért mondják azt, hogy turistaszezon, ha nem szabad rájuk lőni?"
    , "Nem szégyen a kopaszság: Egy szép arcnak kell a hely."
    , "Lehet, hogy tényleg az ufók csinálják a gabonaköröket, de ők is bottal és zsinórral."
    , "Én olyan sokoldalú vagyok, hogy az már majdnem gömb."
    , "Tuti, hogy a tyúk volt előbb. Hülye lett volna Isten ülni egy tojáson!"
    , "Az űrtávcső egy fekete lyukat fedezett fel a Szűz-csillagképben!"
    , "Az igazi férfiak nem pazarolják hajnövesztésre a hormonjaikat."
    , "Ölni tudnék egy Béke Nobel-díjért!"
    , "Az élet akkor kezdődik, amikor a gyerekek elköltöznek és a kutya is megdöglik végre."
    , "Minket nem lehet elbocsátani!!! A rabszolgákat el szokták adni..."
    , "Ha Isten létezik, az az ő baja."
    , "Rólam ez csak úgy kiderülődött. /Medgyessy Péter/"
    , "Szeretnék egy olyan barátnőt végre, akinek a neve nem .jpg-re végződik!"
    , "A bank egy olyan hely, ahol pénzt adnak neked kölcsön, amennyiben bebizonyítod, hogy nincs rá szükséged."
    , "Az első ütést még védtem az arcommal..."
    , "Amikor megszülettem, annyira meglepődtem, hogy másfél évig meg sem szólaltam."
    , "A nőkkel úgy vagyok, mint az elefántokkal. Szívesen megnézem őket, de otthon nem tartanék egyet sem."
    , "A bűnöző olyan rablóösztönnel rendelkező személy, akinek nincs elég pénze, hogy alapítson egy vállalkozást."
    , "Olyan szarul nézel ki, iszol te rendesen?"
    , "Gyógyír a vérnyomásproblémákra: a bor emeli, a pálinka csökkenti, a sör pedig stabilizálja."
    , "Kerüld a csokoládét! Összemegy tőle a ruhád!"
    , "Nem biztos, hogy a pozitív hozzáállás minden problémádat megoldja, de elég embert bosszant ahhoz, hogy érdemes legyen kipróbálni."
    , "Tanulok, mert a tanulásba fektetett energia meghozza a gyümölcsét... és mint tudjuk: a gyümölcsből pálinkát lehet főzni!"
    , "A hisztéria alattomos betegség! A nő kapja meg és a férfi hal bele!"
    , "Jézus megváltoztatta az életedet! Akarod menteni a változásokat? [i/n]"
    , "Az önbizalom egyszerűen az a nyugodt, magabiztos érzés, amit pofára esés előtt érez az ember."
    , "Régen a férfinak meg kellett ölnie a sárkányt, hogy elvehesse a szüzet. Ma már nincsenek szüzek, és a sárkányt kell elvenni... (ismeretlen)"
    , "IKEA poén: Otthon kell összerakni."
    , "Akkora barom, hogy ha ő lenne Zorro, Y-t rajzolna a falra..."
    , "Nem villámlás! A Google Maps-hez csinálják a fényképeket."
    , "Így kell kezdeni egy igazán profi önéletrajzot: 1985. augusztus 19-én születtem a Virginia állambeli Beaverdamtől mintegy 14.000 kilométerre keletre, a Jász-Nagykun-Szolnok megyei Karcagon..."
    , "... nincs olyan képed, amin valamit megbasz egy jegesmedve?"
    , "Annyi esélyed van mint bölcsésznek a command promptnál."
    , "Ki korán kel... az hamarabb ihat."
    , "Ami ingyen van, az biztos megéri az árát."
    , "Meteorológiai előrejelzés: előbb-utóbb tavasz lesz."
    , "Az a legszebb a kopaszságban, hogy az ember hallja a hópelyheket."
    , "A teológia a vallásnak az a része, amihez ész is kell."
    , "Nincs annál jobb vicc, mint amit az ember a beosztottjainak mesél."
    , "A szellemesség művelt pimaszság."
    , "Aki a meleget szereti, hóember nem lehet."
    , "Okos ember más feleségén tanul."
    , "A majom nem esik messze a fájától."
    , "Meglátni és megutálni egy pillanat műve volt csupán."
    , "A szomszéd sírján mindig zöldebb a fű!"
    , "Jobb ma egy alkoholmérgezés, mint holnap egy szívroham."
    , "Ravasz, mint a sakkautomata."
    , "Inkább legyek gazdag és egészséges, mint beteg és szegény!"
    , "Mi a jó az orális szexben? - Az a pár perc csönd."
    , "A házasság nagyon megváltoztat egy kapcsolatot: hirtelen azon veszed észre magad, hogy ágyba bújtál - egy rokonnal."
    , "A házasság egy nagyon költséges módja annak, hogy kitisztíttasd a ruháidat."
    , "Aki azt mondja, hogy a pénz nem boldogít, nem tudja merre vannak a boltok."
    , "Olyan hideg volt, hogy majdnem féjhez mentem. /Shelley Winters színésznő/"
    , "A nő olyan, mint az olimpiai érem. Harcolnod kell érte, aztán egy életen át lóg a nyakadon."
    , "Ha nem tudsz nélkülem élni, akkor miért nem vagy már halott?"
    , "Keresek egy tökéletes párnát. Azt hiszem, valahol a tied mellett van."
    , "Az a jó a maszturbációban, hogy nem kell kiöltözni hozzá."
    , "Én a Norbi módszerrel semmire nem mentem, a Gyurcsány módszerrel viszont szeptember óta hat kilót fogytam... /ismeretlen/"
    , "Ellenzem a párbajokat. Ha engem hívna ki valaki, akkor kedvesen és megbocsátóan megfognám a kezét, elvinném egy csendes helyre és megölném."
    , "Azt hiszem szexeltunk. Legalábbis azt mondta."
    , "Orbit, mint a szádba szorult féreg."
    , "Én nem nőttem fel, nem volt rá pénzünk."
    , "Csirke - olyan állat, amit a vagy a születése előtt, vagy a halála után eszel meg."
    , "Aki megházasodik, az megtudja mi a boldogság, de akkor már késő."
    , "A pszichológia az egyetlen üzletág, ahol az ügyfélnek sosem lehet igaza."
    , "A hülyeség fáj. Majd rájösz ha valaki megun, és leüt..."
    , "A teljes élethez vezető egyik lehetséges út a pályatévesztés."
    , "Nem akkor vagy szabad, ha semmi nem köt sehova, hanem ha ott vagy fogoly, ahol fogoly akarsz lenni."
    , "Tévedni emberi dolog, de már ki lehetne találni más magyarázatot is."
    , "Élj úgy, hogy ha lepereg előtted életed filmje, ne tudd eldönteni, pornó- vagy akciófilmet látsz-e."
    , "Ha az IQ-d 2-vel több lenne már lehetnél sültkrumpli."
    , "Come on baby, light my FILE..."
    , "Kevés vagy, mint Kate Mossban a szilikon inplantátum!"
    , "Az ott pisztoly a zsebében, vagy csak ennyire örül, hogy lát?"
    , "Nem lesz szerencsém. Átment előttem egy fekete cursor."
    , "Ha a nők nem léteznének, a világban a pénznek nem lenne értelme."
    , "Olyan világot élünk, hogy elég ha egyedül élő nyugdíjas leszel egy nagyobb TV-vel."
    , "A szomszédaim nem lehetnek valami gazdagok. Akárhányszor átmegyek hozzájuk, hogy kérjek tőlük valamit, az soha nincs nekik."
    , "Az ősz legszebb pillanata: még keressük, de köze sincs az iskolához!"
    , "Ha sokat eszel, nagyra nősz. Ha nagyra nősz, sokat eszel. Tehát életed végére elérheted az 1 kilométeres magasságot!"
    , "Engem a siker nem ront el. Világ életemben elviselhetetlen voltam."
    , "Istennel nincsen semmi bajom, csak a rajongó táborával."
    , "Antidetoxikációs szindróma = Másnaposság"
    , "Nem az élet utál, hanem a moderátorai."
    , "Úgy szeretkeztek, mintha kihalófélben lévő állatfaj lennének."
    , "A keksz pontosan annyit veszít súlyából, mint amennyi az általa kiszorított tea súlya. /Archimedes törvénye - kicsit másképp/"
    , "Az anyósomat és a sört egyformán szeretem: asztalon, hidegen, felbontva."
    , "Az a durva, amikor a skizofrén két énje összetalálkozik a chaten..."
    , "Egyenjogúságot! A nőket is lehessen tökönrúgni!"
    , "A fizika olyan, mint a szex. Lehetnek gyakorlati eredményei, de nem azért csináljuk."
    , "Remélem szép nap lesz a halálom utáni..."
    , "A békák hogy születnek? Őket is a gólya hozza?"
    , "Családi és személyi szolgáltatások terén piacvezető világcég területi képviselőt keres. Jó kommunikációs készség és alapfokú latin nyelvtudás szükséges. A jelentkezésre kérjük ráírni: 'plébános'."
    , "Az idősebb nők a legjobbak, mert mindig azt hiszik, talán most csinálják utoljára..."
    , "Rossz szerető vagyok. Egyszer kifütyült egy kukkoló."
    , "Akkora köd van, hogy a rendőrök ülnek a jelzőlámpán és kiabálják a színeket!"
    , "Kövesd a fehér rabbit!"
    , "Idegenvezetés: ...és ha hölgyek egy pillanatra abbahagynák a csevegést, hallani lehetne a Niagara vízesés fülsiketítő robaját."
    , "Olyan hülye vagy, hogy ha az agyad beoperálnák egy veréb fejébe, csak hátrafelé tudna ugrálni."
    , "Mindenkiben van valami jó. Bennem például Piroska - mondta a farkas."
    , "Óvatosan dugd! Nehogy az agya kiessen a fejéből!"
    , "Jól nézel ki, hánytál?"
    , "Ha egy nő lefekszik a klónjával, akkor az leszbikus szex, vagy önkielégítés?"
    , "Ha szar az életed, legyél hálás, mert Veled legalább történik valami..."
    , "Ha a munkavégzés olyan egészséges, miért nem a betegekkel csináltatják?"
    , "Az ember életének döntő fázisai: elhiszi, hogy van Mikulás; nem hiszi el, hogy van Mikulás; ő a Mikulás."
    , "Mire megérünk, el is rothadunk."
    , "A tudás csak fájdalomdíj az önmagadhoz vezető úton."
    , "A kreativitás a hülyeség hirtelen elvesztése."
    , "Furcsa jelenségnek számít az, hogy ha a rajzszögek libasorban menetelnek, felém?"
    , "Ameddig nem adsz helyet a lelkedben valakinek, aki éppolyan fontos neked, mint saját magad, addig mindig magányos maradsz."
    , "Szerencsére az életem tele van negatív dolgokkal. Például az AIDS tesztem is az. /droID:242/"
    , "Az igazi bosszú: jól élni nélküled!"
    , "A pokol is csak addig marad jó hely, amig oda nem kerülök. /droID:242/"
    , "Ha Ádám és Éva kínaiak lettek volna, akkor megeszik a kígyót, az almát meg hagyták volna a picsába."
    , "Mikor vetkőztem rájöttem hogy én ezt élvezem. Van egy új életcélom..."
    , "Csak az a nő foglalt, akin fekszenek."
    , "Ha van Isten, akkor visszakapjuk az eredeti vektort. /kísérleti teológia/"
    , "A tűsarok a cipő talpára erősített szerkezet, amit egy nő talált fel, akit egyszer homlokon csókoltak."
    , "Egy főiskolás csak italra költ. Ha éhes lefekszik aludni."
    , "A legoptimistább nép a zsidó. Még nem tudja mekkora, de már levág belőle."
    , "Általában a 'majd holnap' a hét legzsúfoltabb napja."
    , "Amikor apám szeretkezni akart, anyám mindig megmutatta neki a fényképemet."
    , "A Mars-szonda só és jég nyomait találta a Marson. Jelenleg citromot és tequilát keres..."
    , "De szépek a lábaid. Mikor nyitnak?"
    , "A pesszimista az algútban a sötétséget látja, az optimista a fényt, a realista a vonat lámpáit, a mozdonyvezető pedig három hülyét a síneken..."
    , "Háborúzni a békéért olyan mint szeretkezni a szüzességért."
    , "Félig berúgni kidobott pénz."
    , "Egészségünket túlságosan szigorú étrenddel megóvni, unalmas betegség."
    , "Akár tornázhatnék is, a hangulatom már amúgy is rossz."
    , "Kedvenc állatom a bélszín!"
    , "Soha ne nagyítsd fel a hibáidat. Ezt bízd a barátaidra!"
    , "Már 150 könyvem van, de nincs könyvespolcom. Azt senki sem ad kölcsön..."
    , "Azt mondják, hogy csak a szexre gondolok. Ez nem igaz, sokszor eszembe jut a sör is."
    , "Engem a siker nem ront meg, én világéletemben elviselhetetlen voltam."
    , "Hiszek a sárkányokban, a jó emberekben és egyéb fantázia szülte lényekben."
    , "Táncolj inkább, a port jobban bírjuk!"
    , "Szeretkezzünk, elfáradt az ujjam!"
    , "A kivégzéseken a méreginjekciót miért steril tűvel adják be?"
    , "A második legnehezebb dolog a világon: egy nőt felöltöztetni."
    , "A maró gúny is része cégünk szolgáltatásainak."
    , "Tegnap egy masszázsszalonban jártam. Sajnos önkiszolgáló volt."
    , "A dög a rivális hölgy beceneve."
    , "Az ámokfutás a jövő tömegsportja."
    , "A biztonság az a veszély, amit nem érzékelünk."
    , "Az önző csak magára gondol. Az irigy másokra is!"
    , "Ha sebességiszonyod van, használj Windowst!"
    , "Hogy kerülsz ide? Valaki nyitva hagyta a ketrecedet?"
    , "Bizonyos körökben megtiszteltetés, ha azt mondják rád: hogy te mekkora gyökér vagy!"
    , "Az élet szakadatlan küzdelem. Délelőtt az éhséggel, délután az álmossággal."
    , "Ha javulni látod a dolgokat, akkor valami fölött elsiklottál."
    , "Azok a jó női mellek, amik között medál van és nem köldök."
    , "A nőknek csakis a belső értékek számítanak. Pl.: klíma, bőrülés, világított piperetükör, dönthető ülés, mp3, stb."
    , "A halász azért megy ki a tóra, hogy halat fogjon. A horgász meg azért, hogy ne legyen otthon."
    , "Addig igyál, amíg már szépnek tűnik, de még nem akarod elvenni feleségül!"
    , "A nyúl az egy igazi jellem. Ott ül a fűben, de akkor sem szívja!"
    , "Minden reggel ágyba viszem a páromnak a kávét. Neki már csak meg kell darálni..."
    , "Ne dohányozzatok az ágyban! Mi sem dugunk a hamutartóban!"
    , "Egy fiúból akkor válik férfi, ha el tud menni egy pocsolya mellett anélkül, hogy belelépne."
    , "Ha Einsteint az ő korában max. 5 ember értette meg, akkor az én koromban ha senki sem ért meg, zseni vagyok?"
    , "A karaoke bárok a nemzet két legnagyobb csapását ötvözik: azokat az embereket, akik nem bírják az italt azokkal, akik nem bírnak énekelni."
    , "Mondanám, hogy BÚÉK, de igazából leszarom, hogy kinek milyen lesz az éve."
    , "Azok a jó női mellek, amik között medál van és nem köldök..."
    , "A koton a mi nemzedékünk üvegcipellője. Ha egy idegennel találkozol, felveszed, egyet táncolsz benne, azután eldobod."
    , "Ezzel a fejjel már rég fogamzásgátlót kellene reklámoznod."
    , "Nem minden fénylik, ami arany."
    , "Azért jó tengerparton lakni, mert akkor csak három oldalról van hülyékkel körülvéve az ember."
    , "Attól, hogy homokba dugod a fejed, az élet még seggbebasz."
    , "Ha jön a világvége és már nem tudod mit tégy, gyere Romániába, mert mi itt 40 évvel le vagyunk maradva!"
    , "SMS: Szia, öntudatra ébredtem - a telefonközpont."
    , "Mindegy, hogy mit értél el, a temetési meneted hosszát úgyis az időjárás határozza meg."
    , "Ami szép és színes a természetben, az vagy baszni akar, vagy megdöglesz tőle..."
    , "Művirág mag nagy tételben eladó, vagy cserélhető, rózsaszín ferdén fogazott Télapó megsemmisítőre."
    , "LCD monitorom két szabadon választható fehér subpixeljét, 1 db. fekete lyukra cserélem."
    , "Eredeti Bill Gates másodpercek 1000$-os darabáron eladók, vagy légüres térre cserélhetők."
    , "Wikipédia: Bármekkora baromságot is állítasz bizonyítás nélkül, milliók hisznek neked!"
  ];
  
  var last_selected = null;
  
  return {
    getRandomOne: function() {
      var num = (Math.round(Math.random() * 1000) % bsc.length);
      while(num == last_selected) {
        num = (Math.round(Math.random() * 1000) % bsc.length);
      }
      last_selected = num;
      return bsc[num];
    }
  }
})();